### ISSUE TITLE
Error message on Block #3 (editable block) when editing page. 

### ISSUE THREAD

**Issue by amandablum** [ahmadawais/Gutenberg-Boilerplate#12]
I'm only using block # 3.

Have no problems creating the block or editing it, and it renders on front end just fine. But when I revisit Gutenberg editor, the block shows "This block has encountered an error and cannot be previewed.". It cannot be edited. 

![2017-12-08_1021](https://user-images.githubusercontent.com/2366499/33779400-a5dfde5c-dc01-11e7-97ef-00f5434e2455.png)

to reproduce:
add block 3 to page via gutenberg. add text. 
Publish page.
Return to editor. 
editable blocks should be editable, instead say  "This block has encountered an error and cannot be previewed."

**Comment by ahmadawais** [comment]
I'd ask you to try it again with no other plugins active. Coz. I just tested it and it is working fine.

**Comment by amandablum** [comment]
Twenty seventeen, only other plugin is Gutenberg.

**Comment by ahmadawais** [comment]
@amandablum I guess you are talking about block 4 the tweet block.
I can see that it does have an issue.

I am tracking it here → https://github.com/WordPress/gutenberg/pull/3522#issuecomment-350520534

On vacations at the moment, will get back to you as soon as I am back.

**Comment by amandablum** [comment]
I'm talking about block 3, the editable block.

**Comment by ahmadawais** [comment]
I can confirm there's no issue there on Block # 3. 
Tried and tested. You might want to update the Boilerplate as I just pushed out some fixes and the Gutenberg plugin should be at 1.8.1

**Comment by ahmadawais** [comment]
I am tracking the issue with block # 4 here https://github.com/ahmadawais/Gutenberg-Boilerplate/issues/13

**Comment by amandablum** [comment]
Yes you said that. But my issue was with block 3. I will update boilerplate
and get back to you.

**Comment by ahmadawais** [comment]
Sure let me know. Write the content not copy-paste it. I know there is an issue with copy-paste, I suspect it is a problem at Gutenberg's end but I'll investigate

**Comment by ahmadawais** [comment]
👋 

I'd ask you to use [create-guten-block](https://github.com/ahmadawais/create-guten-block) instead of this boilerplate now — I am going to deprecate this project soon and move all the [new examples](https://github.com/ahmadawais/create-guten-block/tree/master/examples) to that project.

**Comment by ryancwalsh** [comment]
Just FYI I've had this same problem with https://github.com/ahmadawais/Gutenberg-Boilerplate/tree/master/block/03-block-editable and even with the official https://github.com/WordPress/gutenberg-examples/tree/master/03-editable. I can't get either of them to work. Maybe create-guten-block will be easier.

**Comment by ahmadawais** [comment]
I promise create-guten-block is easier! 👍
