### ISSUE TITLE
Node install error

### ISSUE THREAD

**Issue by munirkamal** [ahmadawais/Gutenberg-Boilerplate#17]
Hi Ahmad,

First of all thank you so much for this great Gutenberg Boilerplate, it's really useful. 

I am just getting started with it, but getting following error while I run "node install" from the correct directory. Surely I have npm and node installed already. 

    Error: Cannot find module '/Users/MYMACNAMEHERE/Local Sites/blocks-ultimate/app/public/wp-content/plugins/blocks-ultimate/block/02-basic-esnext/install'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

What am I doing wrong?

TIA

**Comment by ahmadawais** [comment]
>First of all thank you so much for this great Gutenberg Boilerplate, it's really useful.

That's very kind of you to say! 💯

I think you are running it in the wrong directory 

```
/02-basic-esnext/install
```
What is install at the end? It shouldn't be there. You should be inside `/02-basic-esnext/`.

Also, do you have the latest Node installed?

**Comment by munirkamal** [comment]
@ahmadawais  thank you for the response. 

I am even not sure about what it's getting the /install because I definitely run it from the correct directory.

I didn't have the latest version of node but I just upgraded to latest stable v9.2.1 and tried to run node install again and end up with the same error :( 

This is the exact error I am getting, something related to module.js it says.

    module.js:544
    throw err;
    ^

     Error: Cannot find module '/Users/MyMacName/Local Sites/blocks-ultimate/app/public/wp-content/plugins/blocks-ultimate/block/02-basic-esnext/install'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3


Any idea what am I doing wrong here? I am kind of new to this build process stuff.

TIA.

**Comment by munirkamal** [comment]
Hi again,

I finally managed to make it work and here is what I did (not sure if that is the correct way, please advice)

1) Deleted the package-lock.json file
2) Run npm install within the block folder
Done!!! Didn't run node install.

Able to build files now. Now I wonder a few things if you may please guide.

1) Will I have to install npm within each of my block as I plan to use JSX and JSNext in all blocks.

2) Will I have to run the build command from each block individually? Is it possible to configure it to make it run once, maybe from the main plugin directory and it build the files for all blocks?

3) How do you build the distribution folder to push on the repo with only the needed files and excluding all extra files & directories like "block.js", "node_modules" folder, all dot files, etc so we get a clean ready to upload/push folder?

4) How about adding loaders to minify the JS and CSS as well to the build process?

Sorry for noob questions here, hoping this will also help other beginners who wish to start using this boilerplate. 

TIA.

**Comment by ahmadawais** [comment]
Glad the issue is resolved. 

1/2 No you don't have to do that. Read the inline docs and modify the build process. I wrote it to help people do just that. Read the Webpack.config.js.
3/ Use .gitignore file for that.
4/ You can def do that.
