### ISSUE TITLE
Run npm build once for all blocks

### ISSUE THREAD

**Issue by truongwp** [ahmadawais/Gutenberg-Boilerplate#2]
Hi there,

Thank you for a great plugin. I have a small problem. If I use ES6 for all blocks, how to config the plugin to run `npm run build` once and it will build all blocks? At the moment, I must run npm for each block. It's not convenient and make the folder size large.

**Comment by ahmadawais** [comment]
Read the source code of `webpack.config.js` file in block #02 and generalize it for a similar pattern or the architecture of your plugin!
