### ISSUE TITLE
[QUESTION] Block Categories...

### ISSUE THREAD

**Issue by mdtauk** [ahmadawais/Gutenberg-Boilerplate#22]
When you create a new Block, does the category need to be one of the existing ones, or could you group a few blocks together in their own category?

**Comment by ajitbohra** [comment]
@mdtauk currently its needs to be one of the existing one https://wordpress.org/gutenberg/handbook/block-api/#category

User defined category will not work.

**Comment by ahmadawais** [comment]
@ajitbohra is right. You can only select from the given categories.

Also @mdtauk I'd much rather have you use create-guten-block → https://github.com/ahmadawais/create-guten-block instead of this old boilerplate.
