### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by strarsis** [ahmadawais/Gutenberg-Boilerplate#23]
Using code from Gutenberg core blocks I get an import error:
```js
/**
 * WordPress dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { PanelBody, RangeControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';
import {
	InspectorControls,
	InnerBlocks,
} from '@wordpress/blocks';
````

````
Uncaught Error: Cannot find module "@wordpress/i18n"
````
How can I use these dependencies (from `@wordpress`)? 
Do I have to install a package first? Configure webpack differently?

**Comment by ahmadawais** [comment]
This repository is depreciated in favor of [create-guten-block](https://github.com/ahmadawais/create-guten-block)

**Comment by strarsis** [comment]
@ahmadawais: Thanks for the notice. I created a new issue in active repository 
(https://github.com/ahmadawais/create-guten-block/issues/53).
