### ISSUE TITLE
Block #3, Block #4 not works

### ISSUE THREAD

**Issue by ruucm-working** [ahmadawais/Gutenberg-Boilerplate#24]
It shows each error in the console

index.js of Gutenberg
```
Jed localization error: 

Error: Domain `GB` was not found.
```

Block # 3
```
Uncaught TypeError: Cannot read property 'children' of undefined
    at block.js?ver=1524087354:16
    at block.js?ver=1524087354:92

```

Block # 4
```
Uncaught TypeError: Cannot read property 'children' of undefined
    at block.js?ver=1524087354:17
    at block.js?ver=1524087354:116
```

My Environment
- WordPress 4.9.6 running Twenty Seventeen theme.
- Gutenberg Version 2.9.2

**Comment by ahmadawais** [comment]
This boilerplate has been depreciated in the favor of create-guten-block try that https://github.com/ahmadawais/create-guten-block

**Comment by ruucm-working** [comment]
@ahmadawais So, is there any sample codes for now? like block 03, 04

**Comment by ahmadawais** [comment]
Try [create-guten-block](https://github.com/ahmadawais/create-guten-block) it creates everything for you. Pretty easy. Seriously you'd love it.

**Comment by ruucm-working** [comment]
awesome Thanks!
