### ISSUE TITLE
Block #3 and Block #4 don't appear

### ISSUE THREAD

**Issue by m-muhsin** [ahmadawais/Gutenberg-Boilerplate#25]
I don't see Block #3 and Block #4 when I try to add a block in the Gutenberg editor. Also, I get the following errors in console when I open the Gutenberg editor:

Jed localization error: 
Error: Domain `GB` was not found. index.js:1:985
TypeError: wp.blocks.source is undefined[Learn More] block.js:16:6
TypeError: wp.blocks.source is undefined[Learn More] block.js:17:6

Looks like source is also deprecated, just like query was!

Thanks for the wonderful plugin!

**Comment by ahmadawais** [comment]
**PRE-DEPRECATION NOTICE**

Instead of this deprecated and no longer-maintained boilerplate, I now recommend you to use my new toolkit called 🔥 ⚛‏ 📦 [`create-guten-block` →](https://github.com/ahmadawais/create-guten-block)
