### ISSUE TITLE
An example for using select control in inspector controls

### ISSUE THREAD

**Issue by truongwp** [ahmadawais/Gutenberg-Boilerplate#3]
I'm building an block and want to have a select control in InspectorControls, but I don't know how to pass the options. I tried some formats of options parameter but all due to js error. Can you show an example for using select control in inspector controls?
Thank you.

**Comment by ahmadawais** [comment]
What did you mean by select controls?

**Comment by truongwp** [comment]
Yes, I want to add a select control to a block, but I don't know how to use SelectControl class

**Comment by ahmadawais** [comment]
@truongwp Why don't you work it out and contribute here? 

Here's more info on it https://github.com/WordPress/gutenberg/tree/master/blocks

**Comment by truongwp** [comment]
I tried to use the SelectControl. I tried some formats of options param but it doesn't work. I tried to find some examples but I can't. Can you give me an example how to use the SelectControl?

**Comment by ahmadawais** [comment]
Oh sure, I am working on a few more examples, just need to document them!

**Comment by lucasstark** [comment]
@truongwp See https://github.com/lucasstark/gutenberg-gravityforms/blob/master/assets/js/block.js#L57

**Comment by truongwp** [comment]
@lucasstark Thank you.
