### ISSUE TITLE
How to Create Multiple Blocks with create-guten-block

### ISSUE THREAD

**Issue by sharazghouri** [ahmadawais/Gutenberg-Boilerplate#46]
I want to create multiple blocks with "create-guten-block ". Is right  approach to code for multiple blocks write in single file  "src/block/block.js".  Here the best thing found 👍  eslint configuration which not ship with other one environment.

**Comment by ahmadawais** [comment]
Hey, @sharazghouri!

Take a look at the [examples](https://github.com/ahmadawais/create-guten-block/tree/master/examples) and their README.md files to see how easy it is to create a mulitple set of blocks in one single plugin. 

Also we are trying to pin down an approach to automate it in ahmadawais/create-guten-block#34
