### ISSUE TITLE
Post settings question

### ISSUE THREAD

**Issue by robbisy** [ahmadawais/Gutenberg-Boilerplate#6]
Hi ahmad
I would like to add categories in the post settings to latest posts Block. But I have no idea on how making that ? 
![gutenberg](https://user-images.githubusercontent.com/18592516/29753704-97746016-8b77-11e7-85b2-c9cda74df5b1.png)

Would you consider adding a section on post settings in your [tutorial](https://github.com/ahmadawais/Gutenberg-Boilerplate#%EF%B8%8F-what-can-you-learn) ?

**Comment by ahmadawais** [comment]
I have a few more examples that I am working on, hang on with me. I'll update about them in the [newsletter](https://WPTakeaway.club/). You could also star the repo.
